=begin pod

=head1 NAME

C<Astro::Almanac> - Provides data on the paths of the Sun, Moon, and
planets

=head1 TEMPORARY DISCLAIMER

C<Astro::Almanac> is a Work in Progress (WIP). Please file an issue if
there are any features you want added. Bug reports (issues) are always
welcome.

=head1 SYNOPSIS

=begin code :lang<raku>

use Astro::Almanac;
use DateTime::Location;

my $loc = DateTime::Location.new: :$name, :$lat, :$lon, :$timezone;
my $a   = Astro::Almanac.new;

# generate one month of daily information in a single JSON file
$a.generate :$loc, :2021year, :1month;

# same for the entire year:
$a.generate :$loc, :2021year;

=end code

=head1 DESCRIPTION

C<Astro::Almanac> provides daily observation data on the Sun, Moon,
and planets, all output as a JSON file named C<astro-data.json>.

Under the covers it uses three fine Perl modules thanks to the
excellent Raku module C<Inline::Perl5>. To install the Perl modules
execute:

=code
# cpanm Astro::Montenbruck::RiseSet::RST
# cpanm Astro::MoonPhase:
# cpanm Astro::Utils

=head1 See also related modules by the same author:

=item L<C<DateTime::Locations>|https://github.com/tbrowder/DateTime-Location>
=item L<C<Calendar>|https://github.com/tbrowder/Calendar>

=head1 AUTHOR

Tom Browder <tom.browder@cpan.org>

=head1 COPYRIGHT AND LICENSE

E<0x00a9> 2020 Tom Browder

This library is free software; you may redistribute it or modify it
under the Artistic License 2.0.

=end pod
