unit class Astro::Almanac:ver<0.0.1>:auth<cpan:TBROWDER>;


=begin pod

=head1 NAME

C<Astro::Almanac> - Provides data on the paths of the Sun, Moon, and planetsth

=head1 SYNOPSIS

=begin code :lang<raku>

use Astro::Almanac;
use DateTime::Location;

my $loc = DateTime::Location.new: :$name, :$lat, :$lon, :$timezone;
my $a   = Astro::Almanac.new;

# generate one month of daily information in a single JSON file
$a.generate :$loc, :2021year, :1month;

# same for the entire year:
$a.generate :$loc, :2021year;

=end code

=head1 DESCRIPTION

C<Astro::Almanac> under the covers uses three fine Perl modules thanks
to the excellent Raku module C<Inline::Perl5>.

To install the Perl modules execute:

=code
# cpanm Astro::Montenbruck::RiseSet::RST
# cpanm Astro::MoonPhase:
# cpanm Astro::Utils


=head1 AUTHOR

Tom Browder <tom.browder@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2020 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
