=begin pod

=head1 NAME

B<Astro::Almanac> - Provides data on the paths of the Sun, Moon, and
planets for a given location on the Earth

Requires installation of Perl module B<Astro::Montenbruck, version 1.24+>.

=head1 SYNOPSIS

=begin code :lang<raku>
use Astro::Almanac;
my $lat =  32.4;  # 32.4 degrees north latitude
my $lon = -86.2;  # 86.2 degrees west longitude
my $a   = Astro::Almanac.new: :$lat, $lon;
# generate one month (Feb) of daily information in a single JSON file
my $file = '2022-02.json';
$a.generate :2022year, :2month, :$file;
# OUTPUT: «See output file '2022-02.json'␤»

# same for the entire year:
$file = '2022.json';
$a.generate :2022year, :$file;
# OUTPUT: «See output file '2022.json'␤»
=end code

=head1 DESCRIPTION

C<Astro::Almanac> provides daily observation data (for a specific
Earth surface location at sea level), on the Sun, Moon,
and planets, all output as a JSON file named C<astro-data-YYYY.json>
(default name, but user-selectable).

Under the covers it uses pieces of one fine Perl module thanks to the
excellent Raku module C<Inline::Perl5>. To install the Perl module
execute, as root: C<cpanm Astro::Montenbruck>. Be sure the version
is at least 1.24.

=head1 See also related modules by the same author:

=item L<C<DateTime::Locations>|https://github.com/tbrowder/DateTime-Location>
=item L<C<DateTime::Julian>|https://github.com/tbrowder/DateTime-Julian>
=item L<C<Calendar>|https://github.com/tbrowder/Calendar>
=item L<C<CalendarConverter>|https://github.com/tbrowder/CalendarConverter>

=head1 CREDITS

The author is indebted to I<Sergey Krushinsky>, the author of the
excellent aid for amateur astronomers, the Perl module B<Astro::Montenbruck>,
available on [CPAN](https://cpan.org). Sergey was very kind and helpful to me
during my learning the rudiments of his module, and was always willing
to listen to my suggestions as a novice user. His module, to me,
is like a I<Swiss Army Knife> for astronomers.

=head1 AUTHOR

Tom Browder (tbrowder@cpan.org)

=head1 COPYRIGHT and LICENSE

Copyright E<0x00a9> 2021 Tom Browder

This library is free software; you may redistribute it or modify it
under the Artistic License 2.0.

=end pod
